### ISSUE TITLE
"Warning: stack.yaml: Unrecognized fields in ProjectAndConfigMonoid" when running `stack setup`

### ISSUE THREAD

**Issue by ocramz** [reinh/reflex-dom-stack-demo#1]
`Warning: ~/reflex-dom-stack-demo/stack.yaml: Unrecognized fields in ProjectAndConfigMonoid: compiler, setup-info`

**Comment by ocramz** [comment]
NB: I hadn't run `stack upgrade --git` before `stack setup`, now I'm checking whether this is the culprit

**Comment by reinh** [comment]
Stack 1.4 is missing some features that HEAD (or possibly 1.8) have. I'm going to mark this as closed but feel free to reopen if the problem persists after upgrading.
