### ISSUE TITLE
Cannot find -ltinfo

### ISSUE THREAD

**Issue by aljce** [reinh/reflex-dom-stack-demo#2]
When running `stack setup` I get the following error:

```
/usr/bin/ld: cannot find -ltinfo
```

**Comment by reinh** [comment]
What platform? (What does `uname -a` say?)

**Comment by aljce** [comment]
That was on arch. I run NixOS now. I cant help investigate the bug regardless :/

**Comment by reinh** [comment]
No worries. If someone else runs into it they can reopen. Thanks!

**Comment by reinh** [comment]
For posterity, this happens when Stack tries to link to the terminfo library for... reasons. It can be fixed most easily by installing ncurses developer libraries. On debian-based systems, this is

```
sudo apt-get install libncurses5-dev
```

**Comment by aljce** [comment]
The problem is on arch you have to install an unsupported packages ltinfo-5 or something from the AUR. Stack needs to hurry up and patch their setup command.

**Comment by reinh** [comment]
Oh. Fun!
