### ISSUE TITLE
Needed to install happy

### ISSUE THREAD

**Issue by tdox** [reinh/reflex-dom-stack-demo#3]
FYI: At one point during the "stack build" process, I got this error message:

Configuring haskell-src-exts-1.16.0.1...
    setup-Simple-Cabal-1.22.4.0-ghcjs-0.2.0.20151029_ghc-7.10.2: The program
    'happy' version >=1.17 is required but it could not be found.

Going to my ~/tmp directory and doing "stack install happy" resolved the problem.

**Comment by reinh** [comment]
Thanks for reporting this.
